#!/usr/bin/env node

var through = require('through2')
var geojsonStream = require('geojson-stream')

var keys = process.argv.slice(2)

process.stdin.pipe(geojsonStream.parse())
.pipe(through.obj(write))
.pipe(geojsonStream.stringify())
.pipe(process.stdout)

function write (feat, _, next) {
  keys.forEach(function (key) {
    feat.properties[key] = feat.properties[key].toUpperCase()
  })
  this.push(feat)
  next()
}
